export const PERMISSIONS = {
  CAMPAIGNS_VIEW: 'campaigns.view',
  CAMPAIGNS_CREATE: 'campaigns.create',
  CAMPAIGNS_UPDATE: 'campaigns.update',
  CAMPAIGNS_DELETE: 'campaigns.delete',
  CAMPAIGNS_ASSIGN_AREAS: 'campaigns.assign_areas',
  CAMPAIGNS_ASSIGN_TEAMS: 'campaigns.assign_teams',
  AREAS_VIEW: 'areas.view',
  AREAS_CREATE: 'areas.create',
  AREAS_UPDATE: 'areas.update',
  AREAS_DELETE: 'areas.delete',
  TEAMS_VIEW: 'teams.view',
  TEAMS_CREATE: 'teams.create',
  TEAMS_UPDATE: 'teams.update',
  TEAMS_DELETE: 'teams.delete',
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  ASSIGNMENTS_VIEW: 'assignments.view',
  ASSIGNMENTS_CREATE: 'assignments.create',
  ASSIGNMENTS_UPDATE: 'assignments.update',
  ASSIGNMENTS_DELETE: 'assignments.delete',
  POSTER_LOCATIONS_MANAGE: 'poster_locations.manage',
  INVITATIONS_MANAGE: 'invitations.manage',
  FEATURE_PERMISSIONS_MANAGE: 'feature_permissions.manage',
} as const

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS]
